### ISSUE TITLE
Error in scoretest.py

### ISSUE THREAD

**Issue by hkmztrk** [HealthML/seak#5]
Hello,

We're using ScoretestNoK function of seak as follows,

```
null_model_score = ScoretestNoK(Y, X)
pv = null_model_score.pv_alt_model(GV)
```

However, we're getting an error when second dimension of `GV` is larger than 1.  (e.g. if GV is (20,1) there is no error, but if GV is (20,2) we are getting the following error: 

```
  File "~/seak/src/seak/scoretest.py", line 183, in pv_alt_model
    squaredform, GPG = self._score(G1)
  File "~/seak/src/seak/scoretest.py", line 432, in _score
    squaredform = ((GtRxY * GtRxY).sum()) * (0.5 / (self.sigma2 * self.sigma2))
  File "~/lib/python3.8/site-packages/numpy/matrixlib/defmatrix.py", line 218, in __mul__
    return N.dot(self, asmatrix(other))
  File "<__array_function__ internals>", line 5, in dot
ValueError: shapes (2,1) and (2,1) not aligned: 1 (dim 1) != 2 (dim 0)
```

If we update line 432 in `scoretest.py` as follows the error is fixed, but we wanted to ask whether this'd be alright. Thanks! 

```
        # squaredform = ((GtRxY * GtRxY).sum()) * (0.5 / (self.sigma2 * self.sigma2)) #original 
        squaredform = ((GtRxY.transpose() * GtRxY).sum()) * (0.5 / (self.sigma2 * self.sigma2)) #updated
```

**Comment by remomomo** [comment]
Hi! Sorry I've only seen this now, I'll have a look and get back to you ASAP

**Comment by hkmztrk** [comment]
Hi @remomomo, thanks a lot for looking into it!

I also want to report a similar case in `coef() `function of ScoretestNoK, where we changed the following line:

`sigma2 = (residuals * residuals).sum() / (self.N - self.D - 1)`

to the below form to get rid of the error:

`sigma2 = (residuals.transpose() * residuals).sum() / (self.N - self.D - 1)`

It'd be great if you could look into this one as well. Best!

**Comment by remomomo** [comment]
I'm not able to reproduce this error. Try the following:

```
from seak.scoretest import ScoretestNoK
import numpy as np

y = np.random.randn(20,1) # shape: (number of individuals), (number of phenotypes = 1)

cov = np.random.randn(20,3) # shape: (number of individuals), (number of covariates)
nullmodel = ScoretestNoK(y, cov)

nullmodel.pv_alt_model(np.random.randn(20,1))
nullmodel.pv_alt_model(np.random.randn(20,2))
```

It's odd that in your implementation `*` appears to call `.dot()` internally, when the correct behavior would seem to be a call to `.multiply()` (https://numpy.org/doc/stable/reference/generated/numpy.multiply.html).

Your fix isn't wrong, it just seems like it shouldn't be necessary.  For an array `x` with dimensions (N,1), writing `(x*x).sum()` in numpy should be equivalent to `x.transpose().dot(x)` (The `.sum()` can be omitted, as the dimension will be (1,1)). I'm not sure in how many places `seak` uses  `(x*x).sum()` as a replacement for `x.transpose().dot(x)` (the other fix you posted appears to be one of them), but if your implementation really does treat `*` as shorthand for `.dot` instead of `.mulitply`, this could lead to problems in many different locations. 

See also:

```
a = np.ones((2,1))
print(a.shape) # (2,1)

b = np.array([0,1])[:,np.newaxis]
print(b.shape) # (2,1)

a * b
```
Doesn't raise an error.

output:
> ```
>(2, 1)
>(2, 1)
>
>array([[0.],
>       [1.]])
>```

**Comment by remomomo** [comment]
let me know if this resolved the issue. Thanks for your interest in `seak`!

**Comment by hkmztrk** [comment]
Thanks @remomomo, it seems at some point our numpy arrays are casted into matrices, that's why * acted as dot function.
